# Generated by Django 5.1.1 on 2024-09-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regi_name', models.TextField(max_length=250)),
                ('regi_email', models.EmailField(max_length=250)),
                ('regi_psw', models.CharField(max_length=250)),
            ],
        ),
    ]
