# Generated by Django 5.1.1 on 2024-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='regi_psw',
            field=models.TextField(max_length=250),
        ),
    ]
