# Generated by Django 5.1.1 on 2024-09-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_registration_regi_psw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.TextField(max_length=250)),
                ('con_email', models.EmailField(max_length=250)),
                ('con_num', models.CharField(max_length=250)),
                ('con_area', models.TextField()),
            ],
        ),
    ]
