# Generated by Django 5.1.1 on 2024-09-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addtoproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=250)),
                ('pro_price', models.FloatField(max_length=250)),
                ('pro_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_user', models.CharField(max_length=250)),
                ('cart_proid', models.IntegerField(null=True)),
                ('cart_name', models.CharField(max_length=250)),
                ('cart_price', models.FloatField(max_length=250)),
                ('cart_image', models.FileField(upload_to='')),
                ('cart_qty', models.IntegerField()),
                ('cart_amount', models.FloatField()),
            ],
        ),
    ]
