# Generated by Django 5.1.1 on 2024-09-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_addtoproduct_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtoproduct',
            name='pro_image',
            field=models.FileField(null=True, upload_to='products'),
        ),
    ]
