# Generated by Django 5.1.1 on 2024-09-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_addtoproduct_pro_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtoproduct',
            name='pro_decc',
            field=models.TextField(null=True),
        ),
    ]
