# Generated by Django 5.1 on 2024-09-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_pro_decc_addtoproduct_pro_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_user', models.CharField(default=None, max_length=250)),
                ('order_name', models.CharField(max_length=250)),
                ('order_price', models.FloatField(max_length=250)),
                ('order_image', models.FileField(null=True, upload_to='')),
                ('order_qty', models.IntegerField()),
                ('order_amount', models.FloatField()),
                ('order_address', models.TextField(null=True)),
                ('order_paytype', models.CharField(max_length=250, null=True)),
                ('order_status', models.IntegerField(default=0)),
            ],
        ),
    ]
