# Generated by Django 5.1 on 2024-09-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_address',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_city',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_country',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_phone',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_postal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
