# Generated by Django 5.1 on 2024-10-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_order_checkout_address_order_checkout_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seats', models.CharField(max_length=15)),
                ('place', models.TextField(max_length=30)),
                ('food', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_user',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
