# Generated by Django 5.1 on 2024-10-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_booktable_alter_order_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
