# Generated by Django 5.1 on 2024-10-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_booktable_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_img', models.FileField(upload_to='')),
                ('user', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
