# Generated by Django 5.2.3 on 2025-06-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='registration',
            name='regi_img',
            field=models.FileField(null=True, upload_to='profile_images'),
        ),
    ]
